// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwd9sisLxcJ8G7TleYrBnvNw8cNyePoEY',
    appId: '1:26143298053:web:cf89c074612af70d43826c',
    messagingSenderId: '26143298053',
    projectId: 'devmob-gestiontaches',
    authDomain: 'devmob-gestiontaches.firebaseapp.com',
    storageBucket: 'devmob-gestiontaches.firebasestorage.app',
    measurementId: 'G-MMMBJ5JFDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqYWlqONhtzPR3zuO1s6qi5c455P4stc',
    appId: '1:26143298053:android:156bdbf01fc27da143826c',
    messagingSenderId: '26143298053',
    projectId: 'devmob-gestiontaches',
    storageBucket: 'devmob-gestiontaches.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1l2lPlirjE8VdORcyQr4qoOSg7_8mL-s',
    appId: '1:26143298053:ios:9c25676b2653a52443826c',
    messagingSenderId: '26143298053',
    projectId: 'devmob-gestiontaches',
    storageBucket: 'devmob-gestiontaches.firebasestorage.app',
    iosBundleId: 'com.example.devmobGestiontaches',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1l2lPlirjE8VdORcyQr4qoOSg7_8mL-s',
    appId: '1:26143298053:ios:9c25676b2653a52443826c',
    messagingSenderId: '26143298053',
    projectId: 'devmob-gestiontaches',
    storageBucket: 'devmob-gestiontaches.firebasestorage.app',
    iosBundleId: 'com.example.devmobGestiontaches',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwd9sisLxcJ8G7TleYrBnvNw8cNyePoEY',
    appId: '1:26143298053:web:c5378d0af5d8998643826c',
    messagingSenderId: '26143298053',
    projectId: 'devmob-gestiontaches',
    authDomain: 'devmob-gestiontaches.firebaseapp.com',
    storageBucket: 'devmob-gestiontaches.firebasestorage.app',
    measurementId: 'G-NPLQK889PX',
  );
}
